---
title: "Neurite orientation dispersion and density imaging in cocaine use disorder"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

Datasets and code for the "Neurite orientation dispersion and density imaging in cocaine use disorder" analysis.

Please let us know if something in the code is incomplete or files are missing or you have any problems by here or in:

jalil.rasgadoto@gmail.com and/or apurva.shah@scmia.edu.in

# About

The present study is the result of the exploration analysis of a subjects sample from The Mexican dataset of substance use disorder patients obtained from the National Institute of Psychiatry in Mexico City. In here, we explored the Neurite orientation dispersion and density imaging, specifically in Viso-values. Perfomed by Eduardo A. Garza-Villarreal and Madhura Ingalhalikar.

# Data

BIDS compliant raw MRI data are available at OpenNeuro: https://openneuro.org/datasets/ds003037/versions/1.0.0

Clinical and Viso-NODDI data are in folder: data/

# Workflow and Code

For check the workflow go to above tab. Csv files and supplementaries are available in source github of this page: data/
